create table if not exists public.agenda_events (
  id bigint generated by default as identity primary key,
  date date not null,
  time time,
  title text not null,
  notes text not null default '',
  category text not null default 'rosa',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.agenda_events enable row level security;
